name: release-please

permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.MAINTENANCE_APP_ID }}
          private-key: ${{ secrets.MAINTENANCE_APP_PEM }}
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ steps.app-token.outputs.token }}
          release-type: go
      - name: Norify on failure
        if: failure()
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_TECH_WEBHOOK }}
          message: |
            The release-please workflow failed.
            Please check the logs for more details
            - **Workflow**: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Notify on Discord
        if: ${{ steps.release-please.outputs.release_created }}
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_TECH_WEBHOOK }}
          message: |
            A new release has been created:
            - **Version**: ${{ steps.release-please.outputs.version }}
            - **Release**: ${{ steps.release-please.outputs.html_url }}
